
# **Homework One**
**Dan Burke**
**August 5, 2023**

# Import Libraries

In [25]:
import pandas as pd
import csv
import numpy as np

# Bespoke Code to Read Data from File
**List of Dictionaries, or some combination of lists, dictionaries and NumPy Arrays**

Below, are two methods created to read a CSV file, then create a list of dictionaries (key = column name | value = list of column values), then transform the list of dictionaries into a pandas dataframe.

This is perhaps the road less travelled as it is much less effort to only utilize the pandas library to read in a csv to a dataframe, however in the spirit of this course, both approaches are applied.

Read in the data from file (Doner Data CSV)

In [128]:
# Method to read a csv file from a local directory,
# then transform that data into a list of dictionaries
def ReadCSVGetListOfDictByColumn(csv_path):
  with open(csv_path) as f:
    colnames = []
    rowData = []
    index = 0
    for row in f:
      if index == 0:
        colnames = row.split(',')
      if index != 0:
        rowsData = row.split(',')
        rowData.append(rowsData)
      index = index + 1;

    #Create the List of Dictionaries
    listOfDicts = {}
    for i in range(0,len(colnames)):
      colStr = colnames[i]
      colDataList = []
      for y in range(0,len(rowData)):
        colDataList.append(rowData[y][i])
      listOfDicts[colStr] = colDataList

    return listOfDicts

# Method to return a dataframe, this leverages the above method
# then iterates over each dictionary and appeand an empty dataframe
def GetDataFrameFromCSV(path):
      dataDicts = ReadCSVGetListOfDictByColumn(path)
      keyNames = dataDicts.keys()
      df = pd.DataFrame()
      for colName in keyNames:
        df[colName] = dataDicts[colName]
        df[colName] = df[colName].astype(float)
      return df

# Implementation of both methods
dataDicts = ReadCSVGetListOfDictByColumn('/content/donors_data.csv')
df = GetDataFrameFromCSV('/content/donors_data.csv')

#Viewing the frist 6 rows of the dataframe to provide a sanity check
# comparable against the following use of the pandas library
df.head()
df.columns

Index(['Row Id', 'Row Id.', 'zipconvert_2', 'zipconvert_3', 'zipconvert_4',
       'zipconvert_5', 'homeowner dummy', 'NUMCHLD', 'INCOME', 'gender dummy',
       'WEALTH', 'HV', 'Icmed', 'Icavg', 'IC15', 'NUMPROM', 'RAMNTALL',
       'MAXRAMNT', 'LASTGIFT', 'totalmonths', 'TIMELAG', 'AVGGIFT', 'TARGET_B',
       'TARGET_D\n'],
      dtype='object')

In [129]:
donerData = pd.read_csv('/content/donors_data.csv')
donerData.head()

,Row Id,Row Id.,zipconvert_2,zipconvert_3,zipconvert_4,zipconvert_5,homeowner dummy,NUMCHLD,INCOME,gender dummy,...,IC15,NUMPROM,RAMNTALL,MAXRAMNT,LASTGIFT,totalmonths,TIMELAG,AVGGIFT,TARGET_B,TARGET_D
0,1,17,0,1,0,0,1,1,5,1,...,1,74,102.0,6.0,5.0,29,3,4.857143,1,5.0
1,2,25,1,0,0,0,1,1,1,0,...,4,46,94.0,12.0,12.0,34,6,9.400000,1,10.0
2,3,29,0,0,0,1,0,2,5,1,...,13,32,30.0,10.0,5.0,29,7,4.285714,1,5.0
3,4,38,0,0,0,1,1,1,3,0,...,4,94,177.0,10.0,8.0,30,3,7.080000,0,0.0
4,5,40,0,1,0,0,1,1,4,0,...,7,20,23.0,11.0,11.0,30,6,7.666667,0,0.0

# Data Exploration

**For each wealth type, what is the average home value of all the donors of that type?**

In [78]:
wealthTypes = donerData['WEALTH'].unique()
wealthHomeVal = []
for x in wealthTypes:
  meanHV = donerData.loc[donerData['WEALTH'] == x, 'HV'].mean()
  wealthHomeVal = meanHV


meanHomeValDf = pd.DataFrame()
meanHomeValDf['wealthType'] = wealthTypes
meanHomeValDf['meanHv'] = wealthHomeVal

meanHomeValDf

   wealthType      meanHv
0           9  817.709877
1           7  817.709877
2           8  817.709877
3           4  817.709877
4           5  817.709877
5           6  817.709877
6           2  817.709877
7           0  817.709877
8           1  817.709877
9           3  817.709877

In [91]:
#Write to CSV file in local directory
meanHomeValDf.to_csv("meanHvByWealthType.csv", sep=',', encoding='utf-8')

# Further Data Inquiry
**Inquiry:**

How does home value correlate to gender?

How does Income correlate to last gift?

How does each zip code correlate to average and last gift and then income correlate to each zip code?

In [188]:
donerData = pd.read_csv('/content/donors_data.csv')

# Method to return the correlation of two columns within the donerData dataframe
def getCorrOf(col1, col2):
  corr = donerData[col1].corr(donerData[col2])
  print("Correlation between ", col1, " and ", col2, "is: ", round(corr, 2))

getCorrOf("HV", "gender dummy")
getCorrOf("gender dummy", "homeowner dummy")
getCorrOf("INCOME", "LASTGIFT")
getCorrOf("INCOME", "AVGGIFT")

getCorrOf("zipconvert_2", "AVGGIFT")
getCorrOf("zipconvert_3", "AVGGIFT")
getCorrOf("zipconvert_4", "AVGGIFT")
getCorrOf("zipconvert_5", "AVGGIFT")

getCorrOf("zipconvert_2", "LASTGIFT")
getCorrOf("zipconvert_3", "LASTGIFT")
getCorrOf("zipconvert_4", "LASTGIFT")
getCorrOf("zipconvert_5", "LASTGIFT")

getCorrOf("zipconvert_2", "LASTGIFT")
getCorrOf("zipconvert_3", "LASTGIFT")
getCorrOf("zipconvert_4", "LASTGIFT")
getCorrOf("zipconvert_5", "LASTGIFT")

getCorrOf("zipconvert_2", "INCOME")
getCorrOf("zipconvert_3", "INCOME")
getCorrOf("zipconvert_4", "INCOME")
getCorrOf("zipconvert_5", "INCOME")

Correlation between  HV  and  gender dummy is:  -0.02
Correlation between  gender dummy  and  homeowner dummy is:  0.0
Correlation between  INCOME  and  LASTGIFT is:  0.11
Correlation between  INCOME  and  AVGGIFT is:  0.13
Correlation between  zipconvert_2  and  AVGGIFT is:  -0.01
Correlation between  zipconvert_3  and  AVGGIFT is:  -0.06
Correlation between  zipconvert_4  and  AVGGIFT is:  -0.03
Correlation between  zipconvert_5  and  AVGGIFT is:  0.08
Correlation between  zipconvert_2  and  LASTGIFT is:  -0.0
Correlation between  zipconvert_3  and  LASTGIFT is:  -0.05
Correlation between  zipconvert_4  and  LASTGIFT is:  -0.03
Correlation between  zipconvert_5  and  LASTGIFT is:  0.07
Correlation between  zipconvert_2  and  LASTGIFT is:  -0.0
Correlation between  zipconvert_3  and  LASTGIFT is:  -0.05
Correlation between  zipconvert_4  and  LASTGIFT is:  -0.03
Correlation between  zipconvert_5  and  LASTGIFT is:  0.07
Correlation between  zipconvert_2  and  INCOME is:  -0.01
Correlation between  zipconvert_3  and  INCOME is:  -0.09
Correlation between  zipconvert_4  and  INCOME is:  -0.02
Correlation between  zipconvert_5  and  INCOME is:  0.09

# Correlation Findings and Conclusion

Generating the correlation between zip codes, income, last and average gift yields interesting results; specifically for "zipconvert_5". This particular zip code was **positivly correlated** for all three adjacent columns. In addition to this zip code having a higher correlation with average and last gift it was also found that last and average gift is positivly correlated with income.

In conlcusion, the higher the income for a particular area of interest (zip code in this analysis) the higher the correlation with average and last gift. "zipconvert_5" is congruent with these findings.

Given the above findings it is recommended to further analyize this data within the context/lens of income and geographic region.

# Further Data Exploration via Grouping

To further explore the data and begin to forumlate questions about this data, it may be advantageous to examine the data via grouping (below).

In [168]:
donerData = pd.read_csv('/content/donors_data.csv')

donerData = donerData.drop(['zipconvert_2','zipconvert_3','zipconvert_4','zipconvert_5'], axis = 1)

gk = donerData.groupby(['NUMCHLD','INCOME'])

In [165]:
gk.first()

                Row Id  Row Id.  homeowner dummy  gender dummy  WEALTH    HV  \
NUMCHLD INCOME
1       1            2       25                1             0       7   698
        2           15      149                0             0       8  1052
        3            4       38                1             0       4  1471
        4            5       40                1             0       8   547
        5            1       17                1             1       9  1399
        6           20      182                0             1       7   995
        7           21      186                1             0       7   936
2       1         1408    10572                0             1       8   551
        2          128      930                0             1       8   623
        3          194     1450                0             1       8   841
        4          163     1213                0             0       3   931
        5            3       29                0             1       8   828
        6          831     6212                1             0       1   672
        7          196     1462                1             1       8  1198
3       2         2009    14942                0             1       8   888
        3          579     4244                1             0       2   556
        4          294     2114                1             0       8   345
        5          408     2964                1             1       8   687
        6          110      785                1             1       8  2968
        7          600     4374                1             0       9  3423
4       1         1120     8306                0             1       8   711
        2          943     7104                0             0       8  1122
        4          274     1973                1             0       8   329
        5          503     3718                1             0       8  1050
        6         1038     7762                1             0       8  1714
        7         1537    11512                1             0       5  2014
5       7         1686    12698                1             0       8   930

                Icmed  Icavg  IC15  NUMPROM  RAMNTALL  MAXRAMNT  LASTGIFT  \
NUMCHLD INCOME
1       1         422    463     4       46     94.00      12.0      12.0
        2         337    402     5       27     50.00      20.0      20.0
        3         484    546     4       94    177.00      10.0       8.0
        4         386    432     7       20     23.00      11.0      11.0
        5         637    703     1       74    102.00       6.0       5.0
        6         372    407    10       83    476.00      25.0      10.0
        7         521    590    11       69     98.00       6.0       5.0
2       1         284    320    21       37    108.00      20.0      15.0
        2         379    388     6       43     37.00       9.0       5.0
        3         464    498     4       29     64.00      10.0       7.0
        4         435    477     5       43    109.00      10.0       9.0
        5         358    376    13       32     30.00      10.0       5.0
        6         192    221    34       72    188.00      25.0      20.0
        7         556    590     6       60    101.00      10.0      10.0
3       2         233    335    33       24     42.00      10.0      10.0
        3         269    290    26       44     60.00      25.0      25.0
        4         220    269    29       27     40.00      10.0      10.0
        5         393    459     9       29     36.00       7.0       3.0
        6         590    631     2       74    161.25      15.0      15.0
        7         689    722     5       47    106.00      25.0      20.0
4       1         323    371    14       22     46.00      20.0      10.0
        2         296    380    20       18     25.00      25.0      25.0
        4         243    289    10       34     80.00      10.0      10.0
        5         538    618     2       21     30.00      20.0      20.0
        6         955    944     0       25     29.00      10.0      10.0
        7         526    566     3       50     79.00       7.0       3.0
5       7         592    632     2       26     33.00      10.0       7.0

                totalmonths  TIMELAG    AVGGIFT  TARGET_B  TARGET_D
NUMCHLD INCOME
1       1                34        6   9.400000         1      10.0
        2                37        7  16.666667         0       0.0
        3                30        3   7.080000         0       0.0
        4                30        6   7.666667         0       0.0
        5                29        3   4.857143         1       5.0
        6                28        6  13.600000         1      23.0
        7                31        2   3.629630         1       4.0
2       1                31        2  13.500000         0       0.0
        2                29        3   3.700000         0       0.0
        3                29        1   8.000000         1       8.0
        4                31        8   6.411765         0       0.0
        5                29        7   4.285714         1       5.0
        6                33       15  12.533333         1      20.0
        7                34        6   6.312500         0       0.0
3       2                28        2   7.000000         1       7.0
        3                31       14  10.000000         0       0.0
        4                29        5  10.000000         1      10.0
        5                17        4   5.142857         1       5.0
        6                19       11   5.201613         0       0.0
        7                31        7  17.666667         0       0.0
4       1                30        3  11.500000         1      20.0
        2                37        5  25.000000         0       0.0
        4                31        5   8.000000         0       0.0
        5                34        2  15.000000         1      20.0
        6                31        1   7.250000         0       0.0
        7                32        5   5.266667         0       0.0
5       7                31        3   6.600000         0       0.0

In [189]:
!jupyter nbconvert --to markdown BurkeDanLab3.ipynb

[NbConvertApp] WARNING | pattern 'BurkeDanLab3.ipynb' matched no files
This application is used to convert notebook files (*.ipynb)
        to various other formats.

        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePreprocessor.enabled=True]
--allow-errors
    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.
    Equivalent to: [--ExecutePreprocessor.allow_errors=True]
--stdin
    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'
    Equivalent to: [--NbConvertApp.from_stdin=True]
--stdout
    Write notebook output to stdout instead of files.
    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]
--inplace
    Run nbconvert in place, overwriting the existing notebook (only
            relevant when converting to notebook format)
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]
--clear-output
    Clear output of current file and save in place,
            overwriting the existing notebook.
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]
--no-prompt
    Exclude input and output prompts from converted document.
    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]
--no-input
    Exclude input cells and output prompts from converted document.
            This mode is ideal for generating code-free reports.
    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]
--allow-chromium-download
    Whether to allow downloading chromium if no suitable version is found on the system.
    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]
--disable-chromium-sandbox
    Disable chromium security sandbox when converting to PDF..
    Equivalent to: [--WebPDFExporter.disable_sandbox=True]
--show-input
    Shows code input. This flag is only useful for dejavu users.
    Equivalent to: [--TemplateExporter.exclude_input=False]
--embed-images
    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.
    Equivalent to: [--HTMLExporter.embed_images=True]
--sanitize-html
    Whether the HTML in Markdown cells and cell outputs should be sanitized..
    Equivalent to: [--HTMLExporter.sanitize_html=True]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
--to=<Unicode>
    The export format to be used, either one of the built-in formats
            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'rst', 'script', 'slides', 'webpdf']
            or a dotted object name that represents the import path for an
            ``Exporter`` class
    Default: ''
    Equivalent to: [--NbConvertApp.export_format]
--template=<Unicode>
    Name of the template to use
    Default: ''
    Equivalent to: [--TemplateExporter.template_name]
--template-file=<Unicode>
    Name of the template file to use
    Default: None
    Equivalent to: [--TemplateExporter.template_file]
--theme=<Unicode>
    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed
    as prebuilt extension for the lab template)
    Default: 'light'
    Equivalent to: [--HTMLExporter.theme]
--sanitize_html=<Bool>
    Whether the HTML in Markdown cells and cell outputs should be sanitized.This
    should be set to True by nbviewer or similar tools.
    Default: False
    Equivalent to: [--HTMLExporter.sanitize_html]
--writer=<DottedObjectName>
    Writer class used to write the
                                        results of the conversion
    Default: 'FilesWriter'
    Equivalent to: [--NbConvertApp.writer_class]
--post=<DottedOrNone>
    PostProcessor class used to write the
                                        results of the conversion
    Default: ''
    Equivalent to: [--NbConvertApp.postprocessor_class]
--output=<Unicode>
    overwrite base name use for output files.
                can only be used when converting one notebook at a time.
    Default: ''
    Equivalent to: [--NbConvertApp.output_base]
--output-dir=<Unicode>
    Directory to write output(s) to. Defaults
                                  to output to the directory of each notebook. To recover
                                  previous default behaviour (outputting to the current
                                  working directory) use . as the flag value.
    Default: ''
    Equivalent to: [--FilesWriter.build_directory]
--reveal-prefix=<Unicode>
    The URL prefix for reveal.js (version 3.x).
            This defaults to the reveal CDN, but can be any url pointing to a copy
            of reveal.js.
            For speaker notes to work, this must be a relative path to a local
            copy of reveal.js: e.g., "reveal.js".
            If a relative path is given, it must be a subdirectory of the
            current directory (from which the server is run).
            See the usage documentation
            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)
            for more details.
    Default: ''
    Equivalent to: [--SlidesExporter.reveal_url_prefix]
--nbformat=<Enum>
    The nbformat version to write.
            Use this to downgrade notebooks.
    Choices: any of [1, 2, 3, 4]
    Default: 4
    Equivalent to: [--NotebookExporter.nbformat_version]

Examples
--------

    The simplest way to use nbconvert is

            > jupyter nbconvert mynotebook.ipynb --to html

            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'rst', 'script', 'slides', 'webpdf'].

            > jupyter nbconvert --to latex mynotebook.ipynb

            Both HTML and LaTeX support multiple output templates. LaTeX includes
            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and
            'classic'. You can specify the flavor of the format used.

            > jupyter nbconvert --to html --template lab mynotebook.ipynb

            You can also pipe the output to stdout, rather than a file

            > jupyter nbconvert mynotebook.ipynb --stdout

            PDF is generated via latex

            > jupyter nbconvert mynotebook.ipynb --to pdf

            You can get (and serve) a Reveal.js-powered slideshow

            > jupyter nbconvert myslides.ipynb --to slides --post serve

            Multiple notebooks can be given at the command line in a couple of
            different ways:

            > jupyter nbconvert notebook*.ipynb
            > jupyter nbconvert notebook1.ipynb notebook2.ipynb

            or you can specify the notebooks list in a config file, containing::

                c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

            > jupyter nbconvert --config mycfg.py

To see all available configurables, use `--help-all`.